spring.application.name=airline-api

spring.datasource.url=jdbc:postgresql://localhost:5432/airline_db
spring.datasource.username=emikaido

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=aviation
spring.jpa.show-sql=true